version: '3.8'

services:

  backend:
    image: radarcovid/authentication
    build:
      context: ./authentication-server-boot/target/docker
      dockerfile: Dockerfile
    environment:
      DATABASE_URL: jdbc:postgresql://postgres:5432/RADARCOVID?schema=authentication
      DATABASE_USER: radarcovid 
      DATABASE_PSW: radarcovid
      DATABASE_SCHEMA: authentication
    depends_on:
      - postgres
    ports:
      - 8080:8080
    networks:
      service:
      persistence:
      
  postgres:
    image: postgres:12-alpine
    environment:
      TZ: Europe/Madrid
      POSTGRES_DB: RADARCOVID
      POSTGRES_USER: radarcovid
      POSTGRES_PASSWORD: radarcovid
      POSTGRES_SCHEMA: public
    volumes:
      - ./sql/:/docker-entrypoint-initdb.d/
    ports:
      - 5432:5432
    networks:
      persistence:
        aliases:
          - postgres
          
  smtp:
    image: namshi/smtp:latest
    ports:
      - "25:25"
    restart: always
    environment:
      MAILNAME: radarcovid
    networks:
      - smtp

networks:
  service:
  persistence:
  smtp:
